Adds E2E test
* Test to run and validate cli

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,7 +38,11 @@ jobs:
         uses: niravpatel27/gh-action-spdx-sbom-generator@v1.0.0
         with:
             version: '0.0.3'   
-      - name: after
+      - name: Check if sbom file generated
         run: |
-          ls
-          ls $GITHUB_WORKSPACE            
+          if [ ! -f "bom-go-mod.spdx" ]; then
+            echo "::error::bom-go-mod.spdx is missing. Must generate using the spdx-sbom-generator cli."
+            exit 1
+          else
+             echo "Success!"            
+          fi           
